/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASK1_H_RPCGEN
#define _ASK1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct str1 {
	int n;
	struct {
		u_int X_len;
		int *X_val;
	} X;
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
};
typedef struct str1 str1;

struct str2 {
	int n;
	struct {
		u_int X_len;
		int *X_val;
	} X;
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
};
typedef struct str2 str2;

struct str3 {
	int n;
	struct {
		u_int X_len;
		int *X_val;
	} X;
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
	float r;
};
typedef struct str3 str3;

struct out1 {
	struct {
		u_int arr1_len;
		float *arr1_val;
	} arr1;
};
typedef struct out1 out1;

struct out2 {
	struct {
		u_int arr2_len;
		float *arr2_val;
	} arr2;
};
typedef struct out2 out2;

#define CALC_PROG 0x23451111
#define innerProduct_vers 1

#if defined(__STDC__) || defined(__cplusplus)
#define innerProduct 1
extern  int * innerproduct_1(str1 *, CLIENT *);
extern  int * innerproduct_1_svc(str1 *, struct svc_req *);
#define average 2
extern  out1 * average_1(str2 *, CLIENT *);
extern  out1 * average_1_svc(str2 *, struct svc_req *);
#define product 3
extern  out2 * product_1(str3 *, CLIENT *);
extern  out2 * product_1_svc(str3 *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define innerProduct 1
extern  int * innerproduct_1();
extern  int * innerproduct_1_svc();
#define average 2
extern  out1 * average_1();
extern  out1 * average_1_svc();
#define product 3
extern  out2 * product_1();
extern  out2 * product_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_str1 (XDR *, str1*);
extern  bool_t xdr_str2 (XDR *, str2*);
extern  bool_t xdr_str3 (XDR *, str3*);
extern  bool_t xdr_out1 (XDR *, out1*);
extern  bool_t xdr_out2 (XDR *, out2*);

#else /* K&R C */
extern bool_t xdr_str1 ();
extern bool_t xdr_str2 ();
extern bool_t xdr_str3 ();
extern bool_t xdr_out1 ();
extern bool_t xdr_out2 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ASK1_H_RPCGEN */
