/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ask1.h"

// Συνάρτηση μενού επιλογών.
int menu(){
    int option;
	printf("-==============================================-\n");
	printf(" 1. Eσωτερικό γινόμενο των δύο διανυσμάτων Χ*Υ\n");
	printf(" 2. Mέση τιμή κάθε διανύσματος: ΕΧ, ΕΥ\n");
	printf(" 3. Γινόμενο r*(Χ+Y)\n");
	printf(" 0. Έξοδος\n");
	printf(" Επιλογή: ");
	scanf("%d", &option);
	printf("-==============================================-\n");

	return option;
}

void calc_prog_1(char *host){
	CLIENT *clnt;
	int  *result_1;
	int i, option=4;
	str1  innerproduct_1_arg;
	out1  *result_2;
	str2  average_1_arg;
	out2  *result_3;
	str3  product_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROG, innerProduct_vers, "udp");
	if(clnt == NULL){
		clnt_pcreateerror (host);
		exit (1);
	}

#endif	/* DEBUG */
	while(option != 0){
		option = menu();
		switch(option){

			// Έξοδος από το πρόγραμμα.
			case 0:
				break;

			// ΕΡΩΤΗΜΑ 1
			case 1:
				printf("Εισάγετε μέγεθος πίνακα n: ");											// Προτροπή χρήστη να εισάγει τιμή για το μέγεθος του πίνακα 'X'.
				scanf("%d", &innerproduct_1_arg.n);
				
				innerproduct_1_arg.X.X_len=innerproduct_1_arg.n;								// Αντιστοίχιση τιμής struct με αυτή του struct ίδιου τύπου που δημιουργήθηκε στο πρόγραμμα αυτό.
				innerproduct_1_arg.Y.Y_len=innerproduct_1_arg.n;								// Αντιστοίχιση τιμής struct με αυτή του struct ίδιου τύπου που δημιουργήθηκε στο πρόγραμμα αυτό.
				innerproduct_1_arg.X.X_val = (int*)malloc(sizeof(int) * innerproduct_1_arg.n);	// Δέσμευση μνήμης για το array του struct.
				innerproduct_1_arg.Y.Y_val = (int*)malloc(sizeof(int) * innerproduct_1_arg.n);	// Δέσμευση μνήμης για το array του struct.

				for(i=0; i<innerproduct_1_arg.n; i++){
					printf("Εισάγετε στοιχείο X: ");
					scanf("%d", &innerproduct_1_arg.X.X_val[i]);	// Εισαγωγή στοιχείου πίνακα Χ από τον χρήστη.
					printf("Εισάγετε στοιχείο Y: ");
					scanf("%d", &innerproduct_1_arg.Y.Y_val[i]);	// Εισαγωγή στοιχείου πίνακα Υ από τον χρήστη.
				}

				result_1 = innerproduct_1(&innerproduct_1_arg, clnt);
				if(result_1 == (int *)NULL){
					clnt_perror (clnt, "call failed");
				}
				else{
					printf("Το εσωτερικό γινόμενο των δύο διανυσμάτων είναι: %d\n", *result_1);
				}
				break;

			// ΕΡΩΤΗΜΑ 2
			case 2:
				
				printf("Εισάγετε μέγεθος πίνακα n: ");									// Προτροπή χρήστη να εισάγει τιμή για το μέγεθος του πίνακα 'X'.
				scanf("%d", &average_1_arg.n);
				average_1_arg.X.X_len=average_1_arg.n;									// Αντιστοίχιση τιμής struct με αυτή του struct ίδιου τύπου που δημιουργήθηκε στο πρόγραμμα αυτό.
				average_1_arg.Y.Y_len=average_1_arg.n;									// Αντιστοίχιση τιμής struct με αυτή του struct ίδιου τύπου που δημιουργήθηκε στο πρόγραμμα αυτό.
				average_1_arg.X.X_val = (int*)malloc(sizeof(int) * average_1_arg.n);	//Δέσμευση μνήμης για το array του struct.
				average_1_arg.Y.Y_val = (int*)malloc(sizeof(int) * average_1_arg.n);	//Δέσμευση μνήμης για το array του struct.

				for(i=0; i<average_1_arg.n; i++){
					printf("Εισάγετε στοιχείο X: ");
					scanf("%d", &average_1_arg.X.X_val[i]);			// Εισαγωγή στοιχείου πίνακα Χ από τον χρήστη.
					printf("Εισάγετε στοιχείο Y: ");
					scanf("%d", &average_1_arg.Y.Y_val[i]);			// Εισαγωγή στοιχείου πίνακα Υ από τον χρήστη.
				}

				result_2 = average_1(&average_1_arg, clnt);
				if(result_2 == (out1 *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else{
					printf("X: %f\n", result_2->arr1.arr1_val[0]);
					printf("Y: %f\n", result_2->arr1.arr1_val[1]);
				}
			break; 

			// ΕΡΩΤΗΜΑ 3
			case 3:
				printf("Εισάγετε μέγεθος πίνακα n: ");									// Προτροπή χρήστη να εισάγει τιμή για το μέγεθος του πίνακα 'X'.
				scanf("%d", &product_1_arg.n);
				product_1_arg.X.X_len=product_1_arg.n;									// Αντιστοίχιση τιμής struct με αυτή του struct ίδιου τύπου που δημιουργήθηκε στο πρόγραμμα αυτό.
				product_1_arg.Y.Y_len=product_1_arg.n;									// Αντιστοίχιση τιμής struct με αυτή του struct ίδιου τύπου που δημιουργήθηκε στο πρόγραμμα αυτό.
				product_1_arg.X.X_val = (int*)malloc(sizeof(int) * product_1_arg.n);	//Δέσμευση μνήμης για το array του struct.
				product_1_arg.Y.Y_val = (int*)malloc(sizeof(int) * product_1_arg.n);	//Δέσμευση μνήμης για το array του struct.

				printf("Εισάγετε αριθμό 'r': ");
				scanf("%f", &product_1_arg.r);						// Εισαγωγή 'r' από τον χρήστη.
				
				for(i=0; i<product_1_arg.n; i++){
					printf("Εισάγετε στοιχείο X: ");
					scanf("%d", &product_1_arg.X.X_val[i]);			// Εισαγωγή στοιχείου πίνακα Χ από τον χρήστη.
					printf("Εισάγετε στοιχείο Y: ");
					scanf("%d", &product_1_arg.Y.Y_val[i]);			// Εισαγωγή στοιχείου πίνακα Υ από τον χρήστη.
				}

				result_3 = product_1(&product_1_arg, clnt);
				if(result_3 == (out2 *)NULL){
					clnt_perror (clnt, "call failed");
				}
				else{
					for(i=0; i < product_1_arg.n; i++){
						printf("Το γινόμενο της %dης σειράς του πίνακα είναι: %f\n",(i+1), result_3->arr2.arr2_val[i]);
					}
				}
			break;

			// Εσφαλμένη τιμή επιλογής μενού
			default:
				printf("Παρακαλώ εισάγετε έγκυρο αριθμό επιλογής..\n");
			break;
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int main(int argc, char *argv[]){
	char *host;

	if(argc < 2){
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calc_prog_1 (host);
	printf("Bye!\n");
	return 0;
}