/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ask1.h"

// ΕΡΩΤΗΜΑ 1: Συνάρτηση για τον υπολογισμό του εσωτερικού γινομένου.
int *innerproduct_1_svc(str1 *argp, struct svc_req *rqstp){
	static int result;
	int i, prod=0;
	for(i=0; i < argp->n; i++){
		prod += argp->X.X_val[i] * argp->Y.Y_val[i];
	}

	result=prod;
	printf("%d\n", result);
	printf("-------------\n");
	return &result;
}

// ΕΡΩΤΗΜΑ 2: Συνάρτηση για τον υπολογισμό της μέσης τιμής.
out1 *average_1_svc(str2 *argp, struct svc_req *rqstp){
	static out1 result;
	int i, sumX=0, sumY=0;

	result.arr1.arr1_len = 2;									// Αρχικοποίηση του μεγέθους 'n' στον πίνακα
	result.arr1.arr1_val = (float*) malloc(2*sizeof(float));	// Δέσμευση μνήμης για το array του struct out1

	for(i = 0; i < argp->n; i++){
		sumX += argp->X.X_val[i];
		sumY += argp->Y.Y_val[i];
	}
	result.arr1.arr1_val[0] = (float)sumX / argp->n;
	result.arr1.arr1_val[1] = (float)sumY / argp->n;
	printf("%f %f\n", result.arr1.arr1_val[0], result.arr1.arr1_val[1]);
	printf("-------------\n");
	return &result;
}

// ΕΡΩΤΗΜΑ 3: Συνάρτηση για τον υπολογισμό του γινομένου r*(X+Y)
out2 *product_1_svc(str3 *argp, struct svc_req *rqstp){
	static out2 result;
	
	int i;
	result.arr2.arr2_len = argp->n;										// Αρχικοποίηση του μεγέθους 'n' στον πίνακα
	result.arr2.arr2_val = (float*) malloc((argp->n)*sizeof(float));	// Δέσμευση μνήμης για το array του struct out1

	for(i = 0; i < argp->n; i++){
		result.arr2.arr2_val[i] = (argp->r) * (argp->X.X_val[i] + argp->Y.Y_val[i]);
		printf("%f\n", result.arr2.arr2_val[i]);
		printf("-------------\n");
	}
	return &result;
}
